language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.0

before_install:
  - composer self-update

install:
  - travis_retry composer install --prefer-dist

script:
  - bin/phpspec run
